# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=30, verbose_name='Matiere')),
                ('note', models.IntegerField(verbose_name='Note /20')),
                ('coef', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='coefficient')),
            ],
            options={
                'verbose_name': 'notes',
            },
        ),
    ]
