# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notesmodel',
            options={'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='date',
            field=models.DateTimeField(default='2017-11-28T21:53:00+01:00', verbose_name='date du contrôle'),
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='description du controle'),
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='nom',
            field=models.CharField(default='2017-11-28T21:53:00+01:00', max_length=255, verbose_name='nom du controle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='typenote',
            field=models.CharField(blank=True, max_length=50, verbose_name='type de note'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='coef',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, verbose_name='coefficient'),
        ),
    ]
