# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20171212_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='date',
            field=models.DateTimeField(verbose_name='date du contrôle'),
        ),
    ]
