# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20171212_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='coef',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4, verbose_name='Coefficient'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='date',
            field=models.DateTimeField(verbose_name='Date du contrôle'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description du contrôle'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='nom',
            field=models.CharField(default='IE', max_length=255, verbose_name='Nom du contrôle'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='typenote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.TypeNote', verbose_name='Type de note'),
        ),
    ]
