# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20171212_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='date',
            field=models.DateField(verbose_name='Date du contrôle'),
        ),
    ]
