# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20171212_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matieremodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
