# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20171212_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='note',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Note /20'),
        ),
    ]
