# Generated by Django 2.0.1 on 2018-01-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ec', models.CharField(max_length=255, verbose_name='Nom')),
                ('coef_ue', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name="Coefficient de l'E.C.")),
                ('desc', models.CharField(max_length=1280, verbose_name="Description de l'E.C.")),
            ],
            options={
                'verbose_name': 'Élément constutif',
            },
        ),
        migrations.CreateModel(
            name='IEmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ie', models.CharField(default='IE', max_length=255, verbose_name='Nom du contrôle')),
                ('note', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('coef_ie', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('EC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolinfo.ECmodel')),
            ],
            options={
                'verbose_name': "Résultat d'un contrôle",
            },
        ),
        migrations.CreateModel(
            name='UEmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ue', models.CharField(max_length=255, verbose_name='Nom')),
                ('coef_ue', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name="Coefficient de l'UE")),
                ('desc', models.CharField(max_length=1280, verbose_name="Description de l'UE")),
            ],
            options={
                'verbose_name': "Unité d'enseignement",
            },
        ),
        migrations.AddField(
            model_name='ecmodel',
            name='UE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scolinfo.UEmodel'),
        ),
    ]
