# Generated by Django 2.0.1 on 2018-01-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmodel',
            name='desc',
            field=models.TextField(verbose_name="Description de l'E.C."),
        ),
        migrations.AlterField(
            model_name='uemodel',
            name='desc',
            field=models.TextField(verbose_name="Description de l'UE"),
        ),
    ]
