# Generated by Django 2.0.1 on 2018-01-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scolinfo', '0002_auto_20180104_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecmodel',
            old_name='coef_ue',
            new_name='coef_ec',
        ),
    ]
